# Generated by Django 5.0.4 on 2024-06-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.CharField(choices=[('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Burgas', 'Burgas'), ('Varna', 'Varna')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
