# Generated by Django 5.0.4 on 2024-06-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='employees_count',
            field=models.IntegerField(default=1, verbose_name='Employees Count'),
        ),
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.CharField(blank=True, choices=[('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Burgas', 'Burgas'), ('Varna', 'Varna')], max_length=20, null=True),
        ),
    ]
