# Generated by Django 5.0.4 on 2024-07-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price_with_discounts',
            new_name='price_with_discount',
        ),
    ]
