# Generated by Django 5.0.4 on 2024-07-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_movie_director_alter_movie_starring_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
